#!/usr/bin/env python3
'''
    A python script that can generate slurm job files. Run from anywhere.
'''

#########################################################################################################
                                              ## Imports ##

import subprocess as sp
import os
import re

#########################################################################################################
                                               ## Paths ##

current_path = os.getcwd()

defaults_path = os.path.join(os.path.expanduser("~"), "bin", "defaults.conf")

template_dir = os.path.join(os.path.expanduser("~"), "bin", "templates")

templates = [f for f in os.listdir(template_dir) if os.path.isfile(os.path.join(template_dir, f))]

#########################################################################################################
                                            ## Gather Info ##

defaults = {}

with open(defaults_path, "r") as f:
    data = f.readlines()

for line in data:
    key, value = line.strip().split("=")
    defaults[key] = value

print("\nYour default values are currently:")
for key, value in defaults.items():
    print(f"{key} = {value}")
print("You may change this in the defaults.conf file.\n")

cluster_info = sp.run(["sinfo", "-h", "-o", "%P|%c|%m|%G|%D"], capture_output=True, text=True, check=True)

all_partitions = []

for line in cluster_info.stdout.split():
    parts = line.split("|")
    all_partitions.append(parts)

cpu_part = []
gpu_part = []

for info in all_partitions:
    if "*" in info[0]:
        info[0] = info[0].rstrip("*")
    if info[3] == "(null)":
        cpu_part.append(info)
    else:
        info[3] = info[3].split(":")[-1]
        gpu_part.append(info)

#########################################################################################################
                                              ## Inputs ##

print("General note: If you need to run something ASAP, it may be a good idea to run an interactive job using \"salloc\". Otherwise, you can use a different QoS.\n")

job_type = input("Do you need CPUs or GPUs? (cpu/[gpu])\n")

if job_type == "gpu" or job_type == "":
    job_type = "gpu"
else:
    job_type = "cpu"

if job_type == "gpu":
    print("Available gpu partitions:")
    print(f"{'Index':>5} {'Partition name':>25} {'GPUs per node':^20} {'Number of nodes':<20}")
    print("---------------------------------------------------------------------------------")
    for i, part in enumerate(gpu_part):
        print(f"{i:>5} {part[0]:>25} {part[3]:^20} {part[4]:<20}")
    while True:
        try:
            partition_choice = int(input("Please enter the index of the partition you would like to use:\n"))
            partition = gpu_part[partition_choice][0]
            break
        except (ValueError, IndexError):
            print("Invalid selection! Please try again.")
    
    
    resources_per_node = int(gpu_part[partition_choice][3])
    max_nodes = int(gpu_part[partition_choice][4])
    max_resources = resources_per_node * max_nodes

    cpn = int(gpu_part[partition_choice][1])

    num_resources = int(input(f"Please specify how many {job_type}s you need:\n"))
    
    if num_resources > max_resources:
        print("You have exceeded the total number of resources available for this partition. Exiting...")
        exit()
    if num_resources % resources_per_node == 0:
        num_nodes = num_resources // resources_per_node
    else:
        print("WARNING: You have asked for a number of resources that is not a multiple of the resources per node. Usually, it is ideal to fully utilitze a node when possible.\n")
        num_nodes = num_resources // resources_per_node + 1

    rec_cpt = int(cpn / (2*num_resources))

else:
    print("Available cpu partitions:")
    print(f"{'Index':>5} {'Partition name':>25} {'CPUs per node':^20} {'Number of nodes':<20}")
    print("-" * (5+25+20+20+3))
    for i, part in enumerate(cpu_part):
        print(f"{i:>5} {part[0]:>25} {part[1]:^20} {part[4]:<20}")
    while True:
        try:
            partition_choice = int(input("Please enter the index of the partition you would like to use:\n"))
            partition = cpu_part[partition_choice][0]
            break
        except (ValueError, IndexError):
            print("Invalid selection! Please try again.")

    print("You are generating a CPU job, so this script will not enforce limits on resource allocation. Check the documentation of your cluster to verify the available resources for your job!\n")

    num_resources = int(input(f"Please specify how many {job_type}s you need:\n"))
    num_nodes = int(input(f"Please specify how many nodes you need:\n"))

chosen_values = {"partition":partition, "num_resources":num_resources, "num_nodes":num_nodes}

print("Templates:")
print(f"{'Index':>5} {'Template name':>20}")
print("-" * (5 + 1 + 20))
for i, file in enumerate(templates):
    print(f"{i:>5} {file:>20}")
template_choice = int(input("Please enter the index of the template you would like to use\n"))

template_path = os.path.join(template_dir, templates[template_choice])

#########################################################################################################

def bracket_replace(original, value):
    open_bracket = original.find("{")
    close_bracket = original.find("}")
    return original[:open_bracket] + value + original[close_bracket+1:]

#########################################################################################################
                                           ## Generate File ##

with open(template_path, "r") as file:
    template_lines = file.readlines()

output_lines = []

for line in template_lines:
    if "{" in line and "}" in line and "SBATCH" in line:
        res = re.findall(r"\{(.*?)\}", line)[0]
        if res in defaults.keys():
            new_line = line.format(**defaults)
        elif res in chosen_values.keys():
            new_line = line.format(**chosen_values)
        elif res == "cpu_per_task" and job_type == "gpu":
            value = input(f"Please select the value you want for cpu-per-task (Recommend {rec_cpt}):\n")
            new_line = bracket_replace(line, value)
        else:
            value = input(f"Please input the value you want for {res}:\n")
            new_line = bracket_replace(line, value)
    else:
        new_line = line
    
    output_lines.append(new_line)

job_path = os.path.join(current_path, defaults["file_name"])

with open(job_path, "w") as out_file:
    out_file.writelines(output_lines)

print(f"Job file titled \"{defaults['file_name']}\" written at {current_path}. It's always a good idea to double check!")



